CREATE TABLE IF NOT EXISTS dev1.BAmatchData (
	matchNum INT NOT NULL,
	eventID INT,
	matchTime VARCHAR(20) NULL,
	actualTime VARCHAR(20) NULL,
	red1 INT NULL,
	red2 INT NULL,
	red3 INT NULL,
	blue1 INT NULL,
	blue2 INT NULL,
	blue3 INT NULL,
	redScore INT NULL,
	blueScore INT NULL,
	redFouls INT NULL,
	blueFouls INT NULL,
	redTechFouls INT NULL,
	blueTechFouls INT NULL,
	redAutoPoints INT NULL,
	blueAutoPoints INT NULL,
	redTelePoints INT NULL,
	blueTelePoints INT NULL,
	redChargeStationPoints INT NULL,
	blueChargeStationPoints INT NULL,
	redLinksRP TINYINT NULL,
	blueLinksRP TINYINT NULL,
	redChargeStationRP TINYINT NULL,
	blueChargeStationRP TINYINT NULL,
	/* add additional entries as described in the BA API once it is released for Charged Up */
	PRIMARY KEY (matchNum),
    FOREIGN KEY (eventID) REFERENCES events (eventID)
) Engine = InnoDB;