cat teamsAll-01.sql > all.sql
cat eventsAll-01.sql >> all.sql
cat events-01.sql >> all.sql
cat teams-01.sql >> all.sql
cat BAschedule-01.sql >> all.sql
cat scouters-01.sql >> all.sql
cat matches-01.sql >> all.sql
cat scoutingRoles-01.sql >> all.sql
cat level2-01.sql >> all.sql
cat analysisTypes-01.sql >> all.sql
cat BAoprs-01.sql >> all.sql
cat BArank-01.sql >> all.sql
cat colorTypes-01.sql >> all.sql
cat BAmatchData-01.sql >> all.sql
cat CEanalysis-01.sql >> all.sql
cat CEanalysisGraphs-01.sql >> all.sql
cat driveTypes-01.sql >> all.sql
cat watch1-01.sql >> all.sql
cat pickList1-01.sql >> all.sql
cat pit-01.sql >> all.sql
cat matchScouting-01.sql >> all.sql