cat teams-01.sql > all.sql
cat eventsAll-01.sql >> all.sql
cat events-01.sql >> all.sql
cat CEteams-01.sql >> all.sql
cat pit-01.sql >> all.sql
cat tmpSchedule-01.sql >> all.sql
cat scouters-01.sql >> all.sql
cat matches-01.sql >> all.sql
cat scoutingRole-01.sql >> all.sql
cat matchScouting-01.sql >> all.sql