ALTER TABLE testing.matches
DROP COLUMN redAutoPts,
DROP COLUMN blueAutoPts,
DROP COLUMN redTelePts,
DROP COLUMN blueTelePts,
DROP COLUMN redEndGmPts,
DROP COLUMN blueEndGmPts,
DROP COLUMN redScore,
DROP COLUMN blueScore,
DROP COLUMN redFouls,
DROP COLUMN blueFouls,
DROP COLUMN redTechFouls,
DROP COLUMN blueTechFouls,
DROP COLUMN redLinksRP,
DROP COLUMN blueLinksRP,
DROP COLUMN redChrgZoneRP,
DROP COLUMN blueChrgZoneRP;

ALTER TABLE testing.matches
ADD COLUMN redTotalCSPts INT NULL,
ADD COLUMN blueTotalCSPts INT NULL,
ADD COLUMN redTotalPts INT NULL,
ADD COLUMN blueTotalPts INT NULL,
ADD COLUMN redLinkPts INT NULL,
ADD COLUMN blueLinkPts INT NULL,
ADD COLUMN redCoopGamePieceCount INT NULL,
ADD COLUMN blueCoopGamePieceCount INT NULL,
	/* Bonuses */
ADD COLUMN redActivationBonus INT NULL,
ADD COLUMN blueActivationBonus INT NULL,
ADD COLUMN redCoopertitionBonus INT NULL,
ADD COLUMN blueCoopertitionBonus INT NULL,
ADD COLUMN redSustainabilityBonus INT NULL,
ADD COLUMN blueSustainabilityBonus INT NULL,
/* fouls */
ADD COLUMN redFouls INT NULL,
ADD COLUMN blueFouls INT NULL,
ADD COLUMN redTechFouls INT NULL,
ADD COLUMN blueTechFouls INT NULL,
	/* autoautonomous */
ADD COLUMN redAutoMoveBonusPts INT NULL,
ADD COLUMN blueAutoMoveBonusPts INT NULL,
ADD COLUMN redAutoGamePieces INT NULL,
ADD COLUMN blueAutoGamePieces INT NULL,
ADD COLUMN redAutoGamePiecePts INT NULL,
ADD COLUMN blueAutoGamePiecePts INT NULL,
ADD COLUMN redAutoCSPts INT NULL,
ADD COLUMN blueAutoCSPts INT NULL,
ADD COLUMN redAutoPts INT NULL,
ADD COLUMN blueAutoPts INT NULL,
    /* teleop */
ADD COLUMN redTeleGamePieces INT NULL,
ADD COLUMN blueTeleGamePieces INT NULL,
ADD COLUMN redTeleGamePiecePts INT NULL,
ADD COLUMN blueTeleGamePiecePts INT NULL,
ADD COLUMN redTelePts INT NULL,
ADD COLUMN blueTelePts INT NULL,
	/* endgame */
ADD COLUMN redEndgameCSPts INT NULL,
ADD COLUMN blueEndgameCSPts INT NULL;
