CREATE TABLE IF NOT EXISTS dev1.matchScouting (
        matchScoutingID INT AUTO_INCREMENT NOT NULL,
        eventID INT NOT NULL,
        matchID INT NOT NULL,
        matchNum INT NULL,
        allianceStationID INT NULL,
        team VARCHAR(10) NOT NULL,
        teamMatchNum INT NULL,
        scoutingStatus INT NULL,
        scouterID INT NULL,
        /* Level 1 Data */
        preStartPos TINYINT NULL,
        preLoad TINYINT NULL,
        preNoShow TINYINT NULL,
        autoMB TINYINT NULL,
        autoRamp TINYINT NULL,
        autoPen TINYINT NULL,
        autoGamePiece1 TINYINT NULL,
        autoGamePiece2 TINYINT NULL,
        autoGamePiece3 TINYINT NULL,
        autoGamePiece4 TINYINT NULL,
        autoScore1 TINYINT NULL,
        autoScore2 TINYINT NULL,
        autoScore3 TINYINT NULL,
        autoScore4 TINYINT NULL,
        teleConeHigh TINYINT NULL,
        teleCubeHigh TINYINT NULL,
        teleConeMid TINYINT NULL,
        teleCubeMid TINYINT NULL,
        teleConeLow TINYINT NULL,
        teleCubeLow TINYINT NULL,
        teleConeCMTY TINYINT NULL,
        teleCubeCMTY TINYINT NULL,
        teleLZPickup TINYINT NULL,
        teleObstructed TINYINT NULL,
        teleWasObstructed TINYINT NULL,
        ramp TINYINT NULL,
        rampAssist TINYINT NULL,
        rampPos TINYINT NULL,
        rampStartTime TINYINT NULL,
        postSubsystemBroke TINYINT NULL,
        postBrokeDown TINYINT NULL,
        postReorientCone TINYINT NULL,
        postShelfPickup TINYINT NULL,
        postGroundPickup TINYINT NULL,
        postGoodPartner TINYINT NULL,
        BAfouls INT NULL,
        BAtechFouls INT NULL,
        BAlinkRP TINYINT NULL,
        BAchargeStationRP TINYINT NULL,
        PRIMARY KEY (matchScoutingID),
        FOREIGN KEY (eventID) REFERENCES events (eventID),
        FOREIGN KEY (matchID) REFERENCES matches (matchID),
        FOREIGN KEY (scouterID) REFERENCES scouters (scouterID),
        FOREIGN KEY (team) REFERENCES teams (team),
        FOREIGN KEY (allianceStationID) REFERENCES allianceStations (allianceStationID)
) Engine = InnoDB;
