CREATE TABLE IF NOT EXISTS dev1.pit (
        pitID INT AUTO_INCREMENT NOT NULL,
        team VARCHAR(10) NOT NULL,
        eventID INT NOT NULL,
        scoutingStatus TINYINT DEFAULT 0,
        scouterID INT NULL,
        robotLength TINYINT NULL,
        robotWidth TINYINT NULL,
        robotHeight TINYINT NULL,
        driveBaseTypeID INT NULL,
        driveMotorTypeID INT NULL,
        manipulatorTypeID INT NULL,
        dedicatedGroundIntake TINYINT NULL,
        superClimbTypeID INT NULL,
        buildTypeID INT NULL,
        centerGravityTypeID INT NULL,
        robotDurability TINYINT NULL,
        buildQuality TINYINT NULL,
        buildComments TINYTEXT NULL,
        electricalQuality TINYINT NULL,
        electricalComments TINYTEXT NULL,
        generalComments TINYTEXT NULL,
        imageLink VARCHAR(150) NULL,
        PRIMARY KEY (pitID),
        FOREIGN KEY (team, eventID) REFERENCES teams (team, eventID),
        FOREIGN KEY (manipulatorTypeID) REFERENCES manipulatorTypes (manipulatorTypeID),
        FOREIGN KEY (driveMotorTypeID) REFERENCES driveMotorTypes (driveMotorTypeID),
        FOREIGN KEY (superClimbTypeID) REFERENCES superClimbTypes (superClimbTypeID),
        FOREIGN KEY (buildTypeID) REFERENCES buildTypes (buildTypeID),
        FOREIGN KEY (driveBaseTypeID) REFERENCES driveBaseTypes (driveBaseTypeID)
) Engine = InnoDB;
