CREATE TABLE IF NOT EXISTS dev2.CEanalysisGraphs (
	CEanalysisGraphsID INT NOT NULL,
	team VARCHAR(10) NOT NULL,
	eventID INT NOT NULL,
	teleLowMean FLOAT NULL,
	teleLowMedian FLOAT NULL,
	teleMidMean FLOAT NULL,
	teleMidMedian FLOAT NULL,
	teleHighMean FLOAT NULL,
	teleHighMedian FLOAT NULL,
	teleTotalMean FLOAT NULL,
	teleTotalMedian FLOAT NULL,
	autoRampMean FLOAT NULL,
	autoRampMedian FLOAT NULL,
	autoGamePiecesMean FLOAT NULL,
	autoGamePiecesMedian FLOAT NULL,
	autoScoreMean FLOAT NULL,
	autoScoreMedian FLOAT NULL,
	teleCommunityMean FLOAT NULL,
	teleCommunityMedian FLOAT NULL,
	teleLZPickupMean FLOAT NULL,
	teleLZPickupMedian FLOAT NULL,
	rampMean FLOAT NULL,
	rampMedian FLOAT NULL,
	/* add more once we determine analysisTypes */
    PRIMARY KEY (CEanalysisGraphsID),
    FOREIGN KEY (eventID) REFERENCES events (eventID),
    FOREIGN KEY (team) REFERENCES teams (team)
) Engine = InnoDB;