CREATE TABLE IF NOT EXISTS dev1.matches (
        matchID INT AUTO_INCREMENT NOT NULL,
        eventID INT NOT NULL,
        matchNum INT NOT NULL,
        red1 VARCHAR(10) NOT NULL,
        red2 VARCHAR(10) NOT NULL,
        red3 VARCHAR(10) NOT NULL,
        blue1 VARCHAR(10) NOT NULL,
        blue2 VARCHAR(10) NOT NULL,
        blue3 VARCHAR(10) NOT NULL,
        /* add alliance data from TBA */
        redTotalCSPts INT NULL,
        blueTotalCSPts INT NULL,
        redTotalPts INT NULL,
        blueTotalPts INT NULL,
        redLinkPts INT NULL,
        blueLinkPts INT NULL,
        redCoopGamePieceCount INT NULL,
        blueCoopGamePieceCount INT NULL,
        /* Bonuses */
        redActivationBonus INT NULL,
        blueActivationBonus INT NULL,
        redCoopertitionBonus INT NULL,
        blueCoopertitionBonus INT NULL,
        redSustainabilityBonus INT NULL,
        blueSustainabilityBonus INT NULL,
        /* fouls */
        redFouls INT NULL,
        blueFouls INT NULL,
        redTechFouls INT NULL,
        blueTechFouls INT NULL,
        /* autoautonomous */
        redAutoMoveBonusPts INT NULL,
        blueAutoMoveBonusPts INT NULL,
        redAutoGamePieces INT NULL,
        blueAutoGamePieces INT NULL,
        redAutoGamePiecePts INT NULL,
        blueAutoGamePiecePts INT NULL,
        redAutoCSPts INT NULL,
        blueAutoCSPts INT NULL,
        redAutoPts INT NULL,
        blueAutoPts INT NULL,
        /* teleop */
        redTeleGamePieces INT NULL,
        blueTeleGamePieces INT NULL,
        redTeleGamePiecePts INT NULL,
        blueTeleGamePiecePts INT NULL,
        redTelePts INT NULL,
        blueTelePts INT NULL,
        /* endgame */
        redEndgameCSPts INT NULL,
        blueEndgameCSPts INT NULL,
        matchTime VARCHAR(10) NULL,
        actualTime VARCHAR(10) NULL,
        PRIMARY KEY (matchID),
        FOREIGN KEY (eventID) REFERENCES events (eventID)
) Engine = InnoDB;
