CREATE TABLE IF NOT EXISTS dev1.matchScoutingL2 (
        matchScoutingL2ID INT AUTO_INCREMENT NOT NULL,
        eventID INT NOT NULL,
        matchID INT NOT NULL,
        matchNum INT NULL,
        allianceStationID INT NULL,
        team VARCHAR(10) NOT NULL,
        teamMatchNum INT NULL,
        scoutingStatus INT NULL,
        scouterID INT NULL,
        preNoShow TINYINT NULL,
        speed TINYINT NULL,
        maneuverability TINYINT NULL,
        sturdiness TINYINT NULL,
        climb TINYINT NULL,
        effort TINYINT NULL,
        scoringEff TINYINT NULL,
        intakeEff TINYINT NULL,
        commentOff TINYTEXT NULL,
        commentDef TINYTEXT NULL,
        goodOffBot TINYINT NULL,
        goodDefBot TINYINT NULL,
        defCommunity TINYINT NULL,
        defCenter TINYINT NULL,
        defLZ TINYINT NULL,        
        PRIMARY KEY (matchScoutingL2ID),
        FOREIGN KEY (eventID) REFERENCES events (eventID),
        FOREIGN KEY (matchID) REFERENCES matches (matchID),
        FOREIGN KEY (scouterID) REFERENCES scouters (scouterID),
        FOREIGN KEY (allianceStationID) REFERENCES allianceStations (allianceStationID)
) Engine = InnoDB;
